/*
Arda Muhammed Çakır
Istanbul Kultur University

Contact: ardacakir200710@gmail.com

!! this project is still under development.

*/


#include <stdio.h>
#include "sqlite3.h"

#define MAX_LEN 50

/* 

 * the program has 2 auth levels, auth level 1 is for employees and 2 for managers. managers can
 - generate codes which is required for editing or adding data to the database (for safety)

 * codes are generated by a algorithm which i didnt made yet. legitimacy of the code
 - will be determined by if the code fits the algorithm or not.

 * only id is required to make operations.

 * need hardcoded employee database. (name, surname, auth_lvl, emp_id)

*/

// function prototypes

static void add_new_customer(void);

// only for editing any data except balance or finance releated datas.
static void edit_customer_data(void);

static void edit_balance(void);

static void view_customer_data(void);

static void menu_screen(void); 

static void login(void);

static sqlite3 *db;

typedef struct{
    char name[MAX_LEN];
    char surname[MAX_LEN];
    char city[MAX_LEN];
    int age;
    int id;
    float balance;
} Customer;


int main(void)
{
    char *err_msg = NULL;
    char *sql_command = "CREATE TABLE IF NOT EXISTS Customers(Name TEXT, Surname TEXT, City TEXT, Age INT, Id INT,Balance INT);";

    int rc = sqlite3_open("data.db", &db);

    
    if (rc != SQLITE_OK){
        printf("Failed to open / create DATABASE file. Quitting...\n");
        return -1;
    }

    rc = sqlite3_exec(db, sql_command, 0, 0, &err_msg);

    if (rc != SQLITE_OK){
        printf("SQL ERROR: %s\n", err_msg);
        sqlite3_free(err_msg);
        return -1;
    }
    else{
        printf("Operation Succesful!\n");
    }

    sqlite3_close(db);

    return 0;
}

static void add_new_customer(void)
{   
    Customer customer;

    // name
    printf("Enter name: ");
    scanf("%s",customer.name);
    // surname
    printf("Enter surname: ");
    scanf("%s",customer.surname);
    // city
    printf("Enter city: ");
    scanf("%s",customer.city);
    // age
    printf("Enter age: ");
    scanf("%d",customer.age);
    // id
    printf("Enter id: ");
    scanf("%d",customer.id);

    // balance : 0
    customer.balance = 0.0f;

    // adding to the sql db


}

static void edit_customer_data(void)
{
    // emptyy
}

static void view_customer_data(void)
{
    // empty
}

static void edit_balance(void)
{
    // emptyy
}

static void login(void)
{
    // empty
}

static void menu_screen(void)
{
    int id;
    unsigned char ch;

    printf("[1] Add a New Customer\n[2] View Customer Information\n[3] Edit Customer Data\n>>>");
    ch = getchar();

    while(ch != '1' && ch != '2' && ch != '3'){
        printf(">>>");
        ch = getchar();
    }
    
    if(ch == '2') {
        printf(">>>");
        scanf("%d",&id);
        view_customer_data();
    }
    else if(ch == '3'){
        printf(">>>");
        scanf("%d",&id);
        edit_customer_data();
        
    }
    else {
        add_new_customer();   
    }

}



